name: PR Preview (Jupyter Book)

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Jupyter Book
        run: |
          python -m pip install --upgrade pip
          pip install jupyter-book
      - name: Clean & build book
        run: |
          jupyter-book clean ./docs --all
          jupyter-book build ./docs
      - name: Upload preview artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-preview
          path: docs/_build/html
          if-no-files-found: error
          retention-days: 7
      - name: Comment link to the run (same-repo PRs only)
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        uses: actions/github-script@v7
        with:
          script: |
            const url = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID}`;
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: `✅ Preview built. Download the **site-preview** artifact from this run:\n\n${url}`
            });

